backend:
  # Use netlify identity as backend
  branch: master
  ### enable below lines for github integration ###
  name: github
  repo: foundations-design/11ty-academic
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "cv" # Used in routes, e.g., /admin/collections/resume
    label: "CV" # Used in the UI
    # folder: "_resume" # The path to the folder where the documents are stored
    # create: true # Allow users to create new documents in this collection
    files: # The fields for each document, usually in front matter
      - label: "Education"
        name: "Education"
        file: "src/_data/cv.yaml"
        fields:
          - label: "Institutions"
            widget: "list"
            name: "Education"
            fields:
              - {label: "Degree", name: "Degree", widget: "string"}
              - {label: "Institution", name: "Institution", widget: "string"}
              - {label: "Location", name: "Location", widget: "string"}
              - {label: "Duration", name: "Duration", widget: "string"}
              - {label: "GPA", name: "GPA", widget: "string", required: false}
              - {label: "Details", name: "Details", widget: "list", required: false}
      # - label: "Work Experience"
      #   name: "Work_Experience"
      #   widget: "list"
      #   fields:
      #     - {label: "Position", name: "Position", widget: "string"}
      #     - {label: "Institution", name: "Institution", widget: "string"}
      #     - {label: "Location", name: "Location", widget: "string"}
      #     - {label: "Duration", name: "Duration", widget: "string"}
      #     - {label: "Responsibilities", name: "Responsibilities", widget: "list"}
      # - label: "Leadership Experience"
      #   name: "Leadership_Experience"
      #   widget: "list"
      #   fields:
      #     - {label: "Position", name: "Position", widget: "string"}
      #     - {label: "Institution", name: "Institution", widget: "string"}
      #     - {label: "Location", name: "Location", widget: "string", required: false}
      #     - {label: "Duration", name: "Duration", widget: "string"}
      #     - {label: "Responsibilities", name: "Responsibilities", widget: "list"}
      # - label: "Skills"
      #   name: "Skills"
      #   widget: "list"
      #   field: {label: "Skill", name: "Skill", widget: "string"}
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
